name = "NarmViz"
uuid = "d2d28525-57f2-465a-853a-c9519fdcef4a"
authors = ["Iztok Fister Jr. <iztok@iztok-jr-fister.eu>", "Marcus Gugacs <marcus@gugacs.me>", "Eva Haring <eva.haring@student.tugraz.at>"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NiaARM = "cb655f37-3f9a-467f-922e-5a165e048db7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
CSV = "0.10.7"
DataFrames = "1.4.4"
NiaARM = "0.3.0"
Plots = "1.38.0"
StatsBase = "0.34.5"
StatsPlots = "0.15.7"
julia = "1.6"
